spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

books:
  message: "Welcome to Micro_Library books microservices api"
  contactDetails:
    name: "Roman Svyshch - Product Owner"
    email: "64b3f3e5b29bbfe451dbfb08d8b604a8a543a9fa0747018dd08c325cafae9cba6355a383261431dd8ddfec7d669b8792"
  onCallSupport:
    - (099) 668-1573
