spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

books:
  message: "Welcome to Micro_Library books microservices api"
  contactDetails:
    name: "Roman Svyshch - Product Owner"
    email: "d2f60969c7f18356054c1ffb8b0b5e89f67331d4f787f935d96996b5ae02dbfd694b417db4322d8c9ce8df1efdc3e283"
  onCallSupport:
    - (099) 668-1573
